import { Share } from 'react-native';

import { config } from '@/config';
import { supabase } from '@/lib/supabase';

/**
 * Records an invite (code generated by the DB) and opens the native share
 * sheet (iMessage-first on iOS). Returns true if the user actually shared.
 *
 * Goes through the send_invite RPC (M13 hardening), not a direct invites
 * insert: the RPC enforces the per-user daily cap that bounds the +50-coins
 * reward (spec §7.8, reward-on-send). Direct inserts are no longer granted, so
 * the old scripted-mint path is closed.
 */
export async function sendInvite(): Promise<boolean> {
  const { data: inviteCode, error } = await supabase.rpc('send_invite', {
    channel_in: 'imessage',
  });
  if (error) throw error;

  const message =
    `I need a rival on ${config.appName} — one real challenge a day, ` +
    `head-to-head. Join me: ${config.invites.shareUrl} (code ${inviteCode})`;

  const result = await Share.share({ message });
  return result.action === Share.sharedAction;
}
