import { Share } from 'react-native';

import { config } from '@/config';
import { supabase } from '@/lib/supabase';

/**
 * Records an invite (code generated by the DB) and opens the native share
 * sheet (iMessage-first on iOS). Returns true if the user actually shared.
 *
 * The coin reward for sending (TUNE 50, spec §7.8) is wired with the
 * server-authoritative coins ledger in M7 — visible stub until then.
 */
export async function sendInvite(userId: string): Promise<boolean> {
  const { data, error } = await supabase
    .from('invites')
    .insert({ inviter_id: userId, channel: 'imessage' })
    .select('invite_code')
    .single();
  if (error) throw error;

  const message =
    `I need a rival on ${config.appName} — one real challenge a day, ` +
    `head-to-head. Join me: ${config.invites.shareUrl} (code ${data.invite_code})`;

  const result = await Share.share({ message });
  return result.action === Share.sharedAction;
}
