/**
 * Central asset registry (spec §4.2, LOCKED pattern): every non-token visual
 * loads from a named slot here. Screens reference slot names ONLY — never
 * inline paths — so replacing the file behind a slot updates the app with
 * zero code change (real art lands in M12).
 *
 * All current files are labeled solid-color placeholders generated by
 * `node scripts/generate-placeholders.js`.
 *
 * Avatar cosmetic art (`boots/*`, `hats/*`, … per spec §14.3) is added when
 * the cosmetics catalog exists (M7/M8): cosmetics reference registry slots via
 * `cosmetics.asset_slot_name`, and those slots join this registry then.
 */
import type { ImageSourcePropType } from 'react-native';

export const assetRegistry = {
  // Brand
  appLogo: require('./placeholders/app-logo.png'),
  loadingScreen: require('./placeholders/loading-screen.png'),

  // Mascot (identity TBD — founder supplies; spec §7.9)
  mascotAvatar: require('./placeholders/mascot-avatar.png'),
  mascotCheer: require('./placeholders/mascot-cheer.png'),
  mascotDefeat: require('./placeholders/mascot-defeat.png'),

  // Mountain world
  mountainBackground: require('./placeholders/mountain-background.png'),
  trail: require('./placeholders/trail.png'),
  flagStart: require('./placeholders/flag-start.png'),
  flagPlanted: require('./placeholders/flag-planted.png'),
  summitState: require('./placeholders/summit-state.png'),

  // Avatar base (layered rig lands in M8; base slot exists from day one)
  hikerBase: require('./placeholders/hiker-base.png'),

  // Crates — one design, five recolors (spec §9.3)
  crateWooden: require('./placeholders/crate-wooden.png'),
  crateBlue: require('./placeholders/crate-blue.png'),
  crateRed: require('./placeholders/crate-red.png'),
  crateYellow: require('./placeholders/crate-yellow.png'),
  crateGold: require('./placeholders/crate-gold.png'),

  // Badges (v1 catalog, spec §6)
  badgeSummitReached: require('./placeholders/badge-summit-reached.png'),
  badgeFirstWin: require('./placeholders/badge-first-win.png'),
  badgeVoteWinner: require('./placeholders/badge-vote-winner.png'),
  badgePerfectWeek: require('./placeholders/badge-perfect-week.png'),
} satisfies Record<string, ImageSourcePropType>;

export type AssetSlot = keyof typeof assetRegistry;

/** Preferred accessor — keeps call sites slot-name-based and typo-safe. */
export function getAsset(slot: AssetSlot): ImageSourcePropType {
  return assetRegistry[slot];
}
